### ISSUE TITLE
bindings/wasm: gen_next_msg_ids for subscriber

### ISSUE THREAD

**Issue by sdellava** [iotaledger/streams#122]
## Description

add gen_next_msg_ids WASM binding for subscriber 

## Motivation

it is missing :)

Explain why this feature is needed.

## Requirements

Write a list of what you want this feature to do.

1. to walk forward in a single branch chain given a message link we currently need to start form the announce link and get all message. It would be very useful be able to walk forward one message by one.

## Are you planning to do it yourself in a pull request?

No.

**Comment by arnauorriols** [comment]
#151 will provide the functionality required without having to expose `gen_next_msg_ids()`

**Comment by sdellava** [comment]
If I've correctly understood the solution proposed simply return all the message in the channel.
It is for sure a useful option, I'm afraid it will lead to poor customer experience in case the channel contains lot of messages.
Getting one message by one, forward or backward, grant the application the possibility to walk the channel presenting progressively the content required. This approch save lot of time and io, specially if the user new for few messages backward.

**Comment by arnauorriols** [comment]
Absolutely! fetching all messages at once looks rather simple on paper but it's unusable at scale. 

In Rust the `Messages` stream will let you iterate the messages one by one (or by chunks, until predicate, filter, etc). It is my intention to explore the integration of the wasm API with [Javascript's AsyncIterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/asyncIterator) and get a similar experience in Javascript and Typescript. However, this PR was already getting long and heavy and have decided to postpone this integration. This is why I added [`Author::fetch_next_msg()`](https://github.com/iotaledger/streams/pull/151/files#diff-91ca48ce367bebe890c88c5c9df2a30e6b145d47c7fd2a9bd7514d5153b94b0fR277-R286) (and the same in `Subscriber`), which fetches only the next message. I realise now that I haven't added this method to the markdown API-reference nor in the examples. Will do before the PR is merged. 

The problem with `gen_next_msg_ids()` is that by itself does not have enough information to know which truly is _the next message_ in the branch(es), that's why `Messages` is needed as the channel traversal mechanism, in which `gen_next_msg_ids()` takes part internally.
