### ISSUE TITLE
A Subscriber with a seed equal to the Author cannot fetch next messages in a private channel

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [iotaledger/streams#159]
## Bug description

If the Subscriber of a Channel is the same as the Author i.e. their seeds are just the same when the Author sends key loads for everyone the implementation does not take into account such Subscriber.

The `receive_keyload` method returns `true`. The messages published can be received by the Subscriber with `receive_msg`, but when the Subscriber calls `fetch_next_msgs` an empty array is returned. 

## Rust version

WASM bindings

- Rust version:

## Hardware specification

What hardware are you using?

- Operating system:
- RAM:
- Cores:
- Device:

## Steps To reproduce the bug

```ts
    const options = new SendOptions("https://api.lb-0.h.chrysalis-devnet.iota.cafe", true);
    const seed = make_seed(20);
    const auth = new Author(seed,options.clone(),ChannelType.SingleBranch);

    let response = await auth.clone().send_announce();
    let ann_link = response.link;
    const ann_link_copy = ann_link.copy();
    console.log("announced at: ", ann_link.toString());
    console.log("Announce message index: " + ann_link.toMsgIndexHex());
  
    let sub = new Subscriber(seed, options.clone());
    const announce = await sub.clone().receive_announcement(ann_link_copy.copy());

    const response2 = await sub.clone().send_subscribe(ann_link_copy.copy());
    await auth.clone().receive_subscribe(response2.link.copy());

    const result = await auth.clone().send_keyload_for_everyone(ann_link_copy.copy());
    const key_load_link_copy = result.link.copy();
    
    const keyLoad = await sub.clone().receive_keyload(key_load_link_copy.copy());
    console.log("Keyload received: ", keyLoad);

    const response_msg = await sub.clone().send_signed_packet(
        key_load_link_copy.copy(),Buffer.from(""),Buffer.from("hello"));

    let seed3 = seed;
    let sub3 = new Subscriber(seed3, options.clone());
    const announce3 = await sub3.clone().receive_announcement(ann_link_copy.copy());
    const keyLoad3 = await sub3.clone().receive_keyload(key_load_link_copy.copy());
    console.log("Keyload received by Subscriber 3: ", keyLoad3);

    // !!!!! This should return a non empty array!!!!!
    const messages_3 = await sub3.clone().fetch_next_msgs();
    console.log("Fetch next messages subscriber 3:", messages_3.length);

    const subs_msg3 = await sub3.clone().receive_msg(response_msg.link.copy());
    console.log("Message received by Subscriber 3: ", Buffer.from(subs_msg3.message.get_masked_payload()).toString());
}
```

## Expected behaviour

The `subs.fetch_next_msgs` shall return the messages and not an empty array. 

## Actual behaviour

An empty array is returned 

## Errors

Paste any errors that you see, including logs, errors, or screenshots.

**Comment by DyrellC** [comment]
Removing the subscription: 
```
const response2 = await sub.clone().send_subscribe(ann_link_copy.copy());
await auth.clone().receive_subscribe(response2.link.copy());
```
Removes this issue, but it does highlight a missing warning in the subscription process. `Subscribers` using the same seed as the `Author` can be created, and should be able to read all messages just fine, but they should not be allowed to be subscribed to the channel, as the `Author` is already registered as a user in it. 

The `Keyload` should already be readable from that subscriber regardless of their being "processed" as a subscriber because the public key of the `Author` is already included in the `Keyload` being sent using `send_keyload_for_everyone`.  

To better help others navigating this problem in the future, we can add a check in the `handle_subscriber` function so that `Author's` will only process  a `Subscriber` if they have not already been included in state store, this way noones states will be overridden (which is what is happening in this case).
