### ISSUE TITLE
As a channel author, I need to be able to restore my Merkle trees

### ISSUE THREAD

**Issue by JakeSCahill** [iotaledger/streams#2]
If I were running a channel and my PC turned off, the state of my Merkle tree would be lost.
To start sending messages on my channel again (without reusing private keys), I'd need to be able to rebuild my Merkle tree.

We should add some sort of interface that allows us to rebuild the Merkle tree from a saved state.

**Comment by Citrullin** [comment]
I guess you can rebuild the link with the ```DefaultTangleLinkGenerator```. (As far as I understand the code, but @semenov-vladyslav can probably tell us more about it).

**Comment by Citrullin** [comment]
[This issue](https://github.com/iotaledger/streams/issues/6) is probably more specific. If we have a method to create a link from an address and tag, you should be able to reconstruct the tree.

**Comment by semenov-vladyslav** [comment]
This issue is a bit more complex and has several aspects to it. Author and Subscriber maintain their internal states which include secret keys, "counter" states, spongos states and trusted public keys.

1. Secret keys are usually generated from "seed". MSS Merkle tree takes up some space (depending on the MT implementation) but building MT is costly operation. NTRU keypair is also generated pseudorandomly. So users must be given a choice whether to explicitly store keys or to just store seeds.
2. "Counter" states rely on the use of a counter. In MSS private key it's the index of leaf WOTS key. Its reuse can lead to signature forgery. In a LinkGenerator reuse of internal counter may lead to message identifiers (`tag` transaction field) to be reused, hence different messages will have the same address.
3. Spongos states in general must be kept secret, otherwise compromise of a spongos state may lead to a message privacy compromise.
4. The integrity of trusted public keys must be checked, otherwise the use of untrusted public key may lead to message privacy or signature compromise.

This suggests that a simple serialization is not enough without additional protection. We have several options:

1. Serialize secrets explicitly (faster, but less compact) vs serialize seeds only (slower, but more compact).
2. Serialize the whole state as one blob (simple, but slow) vs serialize small parts independently (more flexible).
3. Protect serialized blob explicitly (secure, but using which keys?) vs do not protect serialized blob (less secure, application has to deal with protection).
4. Enforce serialization of counters after its use (difficult to implement, potentially slow) vs do not enforce (potentially insecure, there might be practical attacks on MSS/WOTS).

**Comment by JakeSCahill** [comment]
Closing this as it is being addressed here: #14
